"""
Generates the 18 (architecture x tissue_type) entry-point scripts in this
directory from ARCHITECTURE_REGISTRY, mirroring classification's own
mechanical-generation precedent (classification/v2_clean_scripts/
DEVELOPMENT_REPORT.md Sec 2.1) rather than hand-writing 18 near-identical
files. Re-run this after editing the template below or adding/removing an
architecture from the registry -- it overwrites every train_*.py file in
this directory (except itself).

Run from anywhere: python _generate_scripts.py
"""

import sys
from pathlib import Path

THIS_DIR = Path(__file__).resolve().parent
SCRIPTS_DIR = THIS_DIR.parent
sys.path.insert(0, str(SCRIPTS_DIR))
sys.path.insert(0, str(SCRIPTS_DIR.parent))

from models.segmentation.pretrained_registry import ARCHITECTURE_REGISTRY  # noqa: E402

TISSUE_TYPES = ["palpebral", "forniceal_palpebral"]

TEMPLATE = '''"""
Entry point: 12-trial Optuna hyperparameter search for the "{tier}" {family}
architecture `{arch_key}` (~see models/segmentation/pretrained_registry.py's
own self-test output for the measured parameter count), against the
raw-photo-aligned `{tissue_type}` tissue dataset, via the shared engine in
trainer_engine.py. Auto-generated by _generate_scripts.py -- edit the
registry or the generator template, not this file directly.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from dataset import AlignedConjunctivaSegmentationDataset  # noqa: E402
from models.segmentation.pretrained_registry import ARCHITECTURE_REGISTRY  # noqa: E402
from trainer_engine import run_study  # noqa: E402

if __name__ == "__main__":
    entry = ARCHITECTURE_REGISTRY["{arch_key}"]
    run_study(
        model_cls=None,
        model_name="{model_name}",
        dataset_cls=AlignedConjunctivaSegmentationDataset,
        tissue_type="{tissue_type}",
        image_size=entry["input_size"],
        build_model=entry["build_fn"],
        n_trials=12,
    )
'''


def main():
    generated = []
    for arch_key, entry in ARCHITECTURE_REGISTRY.items():
        for tissue_type in TISSUE_TYPES:
            model_name = f"{arch_key}_{tissue_type}"
            file_path = THIS_DIR / f"train_{model_name}.py"
            file_path.write_text(
                TEMPLATE.format(
                    tier=entry["tier"],
                    family=entry["family"],
                    arch_key=arch_key,
                    tissue_type=tissue_type,
                    model_name=model_name,
                ),
                encoding="utf-8",
            )
            generated.append(file_path.name)

    print(f"Generated {len(generated)} entry-point scripts in {THIS_DIR}:")
    for name in generated:
        print(f"  {name}")


if __name__ == "__main__":
    main()
