"""
Entry point: 12-trial Optuna hyperparameter search for the "base" hybrid
architecture `hybrid_base_coatnet0_unet` (~see models/segmentation/pretrained_registry.py's
own self-test output for the measured parameter count), against the
raw-photo-aligned `forniceal_palpebral` tissue dataset, via the shared engine in
trainer_engine.py. Auto-generated by _generate_scripts.py -- edit the
registry or the generator template, not this file directly.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from dataset import AlignedConjunctivaSegmentationDataset  # noqa: E402
from models.segmentation.pretrained_registry import ARCHITECTURE_REGISTRY  # noqa: E402
from trainer_engine import run_study  # noqa: E402

if __name__ == "__main__":
    entry = ARCHITECTURE_REGISTRY["hybrid_base_coatnet0_unet"]
    run_study(
        model_cls=None,
        model_name="hybrid_base_coatnet0_unet_forniceal_palpebral",
        dataset_cls=AlignedConjunctivaSegmentationDataset,
        tissue_type="forniceal_palpebral",
        image_size=entry["input_size"],
        build_model=entry["build_fn"],
        n_trials=12,
    )
