"""
Generates the entry-point scripts in this directory -- one per combo that
actually completed the Optuna sweep (Segmentation/scripts/train_pretrained/),
mirroring that directory's own _generate_scripts.py mechanical-generation
pattern. Combos are discovered DYNAMICALLY by globbing the real
*_study_summary.json files under Segmentation/scripts/train_pretrained/
output/segmentation_sweep_results*/logs/ -- not hardcoded -- reading each
combo's own best_params (learning_rate, weight_decay, loss_fn) directly, the
same "discover combos from a prior sweep's results, don't hand-copy them"
pattern classification/step1_cv_harness/cv_config.py's discover_combos()
already established for the identical situation. Stays correct automatically
if those summary files are ever regenerated; naturally produces exactly the
12 completed combos and skips the 6 that OOM'd (no summary file exists for
those, since a crashed run writes no output at all).

Re-run this after editing the template below, or after re-running
train_pretrained/'s Optuna sweep and getting different best_params -- it
overwrites every train_kfold_*.py file in this directory (except itself).

Run from anywhere: python _generate_scripts.py
"""

import json
import sys
from pathlib import Path

THIS_DIR = Path(__file__).resolve().parent
SCRIPTS_DIR = THIS_DIR.parent
PROJECT_ROOT = SCRIPTS_DIR.parent
sys.path.insert(0, str(SCRIPTS_DIR))
sys.path.insert(0, str(PROJECT_ROOT))

from models.segmentation.pretrained_registry import ARCHITECTURE_REGISTRY  # noqa: E402

SWEEP_OUTPUT_DIR = SCRIPTS_DIR / "train_pretrained" / "output"
TISSUE_TYPES = ["palpebral", "forniceal_palpebral"]

TEMPLATE = '''"""
Entry point: 3-fold re-training of the "{tier}" {family} architecture
`{arch_key}` (see models/segmentation/pretrained_registry.py's own
self-test output for the measured parameter count) against the
raw-photo-aligned `{tissue_type}` tissue dataset, via the shared K-fold
engine in kfold_engine.py. Fixed hyperparameters below are this combo's
own best_params from its Optuna sweep study_summary.json (NOT re-tuned
here -- see kfold_engine.py's module docstring for why).
Auto-generated by _generate_scripts.py -- edit the discovered
study_summary.json / the generator template, not this file directly.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from models.segmentation.pretrained_registry import ARCHITECTURE_REGISTRY  # noqa: E402
from kfold_engine import run_kfold_study  # noqa: E402

if __name__ == "__main__":
    entry = ARCHITECTURE_REGISTRY["{arch_key}"]
    run_kfold_study(
        model_name="{model_name}",
        build_model=entry["build_fn"],
        tissue_type="{tissue_type}",
        image_size=entry["input_size"],
        learning_rate={learning_rate},
        weight_decay={weight_decay},
        loss_fn_name="{loss_fn_name}",
        n_folds=3,
    )
'''


def discover_combos() -> list:
    """Globs every *_study_summary.json under the Optuna sweep's 3 tier
    output dirs, returning (model_name, arch_key, tissue_type, best_params)
    for each -- exactly the 12 combos that actually completed."""
    combos = []
    for summary_path in sorted(SWEEP_OUTPUT_DIR.glob("segmentation_sweep_results*/logs/*_study_summary.json")):
        with open(summary_path) as f:
            summary = json.load(f)
        model_name = summary["model_name"]

        tissue_type = None
        # Longest-suffix-first: "_palpebral" is itself a suffix of
        # "_forniceal_palpebral", so checking "palpebral" before
        # "forniceal_palpebral" would wrongly match every forniceal combo
        # too and strip only part of its real suffix (caught by actually
        # running this: 6 forniceal combos landed on a bogus arch_key like
        # "..._forniceal", which doesn't exist in ARCHITECTURE_REGISTRY).
        for candidate in sorted(TISSUE_TYPES, key=len, reverse=True):
            if model_name.endswith(f"_{candidate}"):
                tissue_type = candidate
                arch_key = model_name[: -len(f"_{candidate}")]
                break
        if tissue_type is None:
            print(f"WARNING: could not determine tissue_type from model_name {model_name!r}, skipping.")
            continue

        if arch_key not in ARCHITECTURE_REGISTRY:
            print(f"WARNING: {arch_key!r} (from {summary_path.name}) not found in ARCHITECTURE_REGISTRY, skipping.")
            continue

        combos.append(
            {
                "model_name": model_name,
                "arch_key": arch_key,
                "tissue_type": tissue_type,
                "best_params": summary["best_params"],
            }
        )
    return combos


def main():
    combos = discover_combos()
    generated = []
    for combo in combos:
        arch_key = combo["arch_key"]
        entry = ARCHITECTURE_REGISTRY[arch_key]
        model_name = combo["model_name"]
        best_params = combo["best_params"]

        file_path = THIS_DIR / f"train_kfold_{model_name}.py"
        file_path.write_text(
            TEMPLATE.format(
                tier=entry["tier"],
                family=entry["family"],
                arch_key=arch_key,
                tissue_type=combo["tissue_type"],
                model_name=model_name,
                learning_rate=best_params["learning_rate"],
                weight_decay=best_params["weight_decay"],
                loss_fn_name=best_params["loss_fn"],
            ),
            encoding="utf-8",
        )
        generated.append(file_path.name)

    print(f"Discovered {len(combos)} completed combos, generated {len(generated)} entry-point scripts in {THIS_DIR}:")
    for name in generated:
        print(f"  {name}")

    expected_total = len(ARCHITECTURE_REGISTRY) * len(TISSUE_TYPES)
    if len(combos) < expected_total:
        missing = expected_total - len(combos)
        print(
            f"\n{missing} of {expected_total} possible combos have no study_summary.json "
            f"(the 6 Transformer-family combos OOM'd on Kaggle -- see "
            f".project_memory/kaggle/01_kaggle_notes.md) and were correctly skipped, not an error."
        )


if __name__ == "__main__":
    main()
