"""
Entry point: 3-fold re-training of the "strong" cnn architecture
`cnn_strong_convnext_large_unet` (see models/segmentation/pretrained_registry.py's own
self-test output for the measured parameter count) against the
raw-photo-aligned `forniceal_palpebral` tissue dataset, via the shared K-fold
engine in kfold_engine.py. Fixed hyperparameters below are this combo's
own best_params from its Optuna sweep study_summary.json (NOT re-tuned
here -- see kfold_engine.py's module docstring for why).
Auto-generated by _generate_scripts.py -- edit the discovered
study_summary.json / the generator template, not this file directly.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from models.segmentation.pretrained_registry import ARCHITECTURE_REGISTRY  # noqa: E402
from kfold_engine import run_kfold_study  # noqa: E402

if __name__ == "__main__":
    entry = ARCHITECTURE_REGISTRY["cnn_strong_convnext_large_unet"]
    run_kfold_study(
        model_name="cnn_strong_convnext_large_unet_forniceal_palpebral",
        build_model=entry["build_fn"],
        tissue_type="forniceal_palpebral",
        image_size=entry["input_size"],
        learning_rate=0.000684792009557478,
        weight_decay=2.62108787826544e-06,
        loss_fn_name="focal_tversky",
        n_folds=3,
    )
